export function asset(path) {
  return path.split("/").map(encodeURIComponent).join("/");
}

export const CATEGORIES = [
  { id: "brand", label: "品牌设计" },
  { id: "illustration", label: "插画设计" },
  { id: "visual", label: "视觉设计" },
  { id: "ip", label: "IP 设计" },
];

export const PROJECTS = [
  {
    id: "canplus",
    title: "参加 CAN+",
    category: "brand",
    summary: "参加学院品牌系统：标识、物料与节日礼盒延展。",
    cover: "作品/参加canplus.jpg",
    images: [
      "品牌设计/参加CANPLUS/1.canplus-logo说明.jpg",
      "品牌设计/参加CANPLUS/2.canplus设计物料.jpg",
      "品牌设计/参加CANPLUS/3.canplus设计.jpg",
      "品牌设计/参加CANPLUS/4.canplus教师节礼盒.jpg",
    ],
  },
  {
    id: "hongyuan",
    title: "鸿源物业",
    category: "brand",
    summary: "物业品牌形象、物料与小程序界面设计。",
    cover: "作品/鸿源物业.jpg",
    images: [
      "品牌设计/鸿源物业/1.泓源物业.jpg",
      "品牌设计/鸿源物业/2.鸿源物业设计说明.jpg",
      "品牌设计/鸿源物业/3.鸿源物业物料展示.jpg",
      "品牌设计/鸿源物业/4.鸿源物业小程序界面.jpg",
    ],
  },
  {
    id: "bushang",
    title: "不尚家居",
    category: "brand",
    summary: "家居品牌标识、宣传册与落地物料。",
    cover: "作品/不尚家居.jpg",
    images: [
      "品牌设计/不尚家居/1.不尚.jpg",
      "品牌设计/不尚家居/2.不尚设计说明.jpg",
      "品牌设计/不尚家居/3.物料展示.jpg",
      "品牌设计/不尚家居/4.不尚宣传册.jpg",
    ],
  },
  {
    id: "anniversary",
    title: "参加五周年",
    category: "visual",
    summary: "周年主视觉、物料与现场应用。",
    cover: "作品/参加五周年.jpg",
    images: [
      "视觉设计/参加五周年/参加五周年视觉.jpg",
      "视觉设计/参加五周年/参加五周年视觉介绍.jpg",
      "视觉设计/参加五周年/物料展示.jpg",
    ],
  },
  {
    id: "xinzhi",
    title: "新质生产力实验室",
    category: "visual",
    summary: "实验室主视觉与海报系统。",
    cover: "作品/新质生产力实验室.jpg",
    images: [
      "视觉设计/新质生产力实验室/新质生产力主视觉.jpg",
      "视觉设计/新质生产力实验室/海报展示.jpg",
    ],
  },
  {
    id: "xun",
    title: "循：气候技术论坛",
    category: "visual",
    summary: "气候技术引领城市循环新经济论坛主视觉与海报。",
    cover: "作品/循：气候技术引领城市循环新经济论坛.jpg",
    images: [
      "视觉设计/循：气候技术引领城市循环新经济论坛/主视觉展示.jpg",
      "视觉设计/循：气候技术引领城市循环新经济论坛/循：海报排版.jpg",
    ],
  },
  {
    id: "forum2026",
    title: "消费科技融合创新论坛",
    category: "visual",
    summary: "论坛主视觉、延展物料与现场。",
    cover: "作品/2026消费科技融合创新论坛.jpg",
    images: [
      "视觉设计/2026消费科技融合创新论坛/论坛主视觉.jpg",
      "视觉设计/2026消费科技融合创新论坛/论坛延展物料.jpg",
      "视觉设计/2026消费科技融合创新论坛/现场拍摄.jpg",
    ],
  },
  {
    id: "visuals",
    title: "其他视觉合集",
    category: "visual",
    summary: "课程与论坛主视觉合集。",
    cover: "作品/其他视觉展示.jpg",
    images: [
      "视觉设计/其他视觉合集展示/无界消费创新营主视觉.jpg",
      "视觉设计/其他视觉合集展示/无界消费创新营7期主视觉.jpg",
      "视觉设计/其他视觉合集展示/美味中国创新营三期主视觉.jpg",
      "视觉设计/其他视觉合集展示/美味中国创新营四期主视觉.jpg",
      "视觉设计/其他视觉合集展示/高参学堂京铭班主视觉.jpg",
      "视觉设计/其他视觉合集展示/WRC巅峰论坛主视觉.jpg",
    ],
  },
  {
    id: "stickers",
    title: "贴纸插画",
    category: "illustration",
    summary: "企鹅、小猫、北极熊等角色贴纸系列。",
    cover: "作品/贴纸插画.jpg",
    images: [
      "插画设计/贴纸插画/贴纸插画说明.jpg",
      "插画设计/贴纸插画/企鹅贴纸插画.jpg",
      "插画设计/贴纸插画/企鹅贴纸插画-秋季版.jpg",
      "插画设计/贴纸插画/小猫贴纸插画.jpg",
      "插画设计/贴纸插画/北极熊贴纸插画.jpg",
      "插画设计/贴纸插画/小鸭子贴纸插画.jpg",
      "插画设计/贴纸插画/赛博猪贴纸插画.jpg",
    ],
  },
  {
    id: "solar",
    title: "十二节气插画",
    category: "illustration",
    summary: "节气主题插画，用于课程与社交传播。",
    cover: "作品/十二节气插画.jpg",
    images: [
      "插画设计/十二节气插画/创作说明-集合展示.jpg",
      "插画设计/十二节气插画/立春-微信.jpg",
      "插画设计/十二节气插画/雨水-微信.jpg",
      "插画设计/十二节气插画/惊蛰-微信.jpg",
      "插画设计/十二节气插画/春分-微信.jpg",
      "插画设计/十二节气插画/谷雨-二维码.jpg",
      "插画设计/十二节气插画/立夏.jpg",
      "插画设计/十二节气插画/小满-微信.jpg",
      "插画设计/十二节气插画/芒种-微信.jpg",
      "插画设计/十二节气插画/夏至-微信.jpg",
      "插画设计/十二节气插画/立秋-微信.jpg",
      "插画设计/十二节气插画/处暑-微信.jpg",
      "插画设计/十二节气插画/白露-微信.jpg",
      "插画设计/十二节气插画/秋分-微信.jpg",
      "插画设计/十二节气插画/寒露-微信.jpg",
      "插画设计/十二节气插画/立冬-微信.jpg",
      "插画设计/十二节气插画/小雪-微信.jpg",
      "插画设计/十二节气插画/大雪-微信.jpg",
      "插画设计/十二节气插画/小寒-微信.jpg",
      "插画设计/十二节气插画/元宵-微信.jpg",
      "插画设计/十二节气插画/五一1.jpg",
    ],
  },
  {
    id: "map",
    title: "产业地图插画",
    category: "illustration",
    summary: "参加产业地图插画与拼图印刷。",
    cover: "作品/产业地图.jpg",
    images: [
      "插画设计/产业地图插画/作品创作说明.jpg",
      "插画设计/产业地图插画/参加地图-拼图印刷.jpg",
    ],
  },
  {
    id: "jiajia",
    title: "IP · 加加",
    category: "ip",
    summary: "参加学院 IP 形象加加。",
    cover: "作品/IP-加加.jpg",
    pdf: "IP设计/IP-加加.pdf",
    images: ["作品/IP-加加.jpg"],
  },
];

export const HOME_ORDER = [
  "canplus",
  "jiajia",
  "bushang",
  "stickers",
  "hongyuan",
  "anniversary",
  "solar",
  "map",
];
